# Generated by Django 2.1.8 on 2020-03-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/2020/03/touxiang.jpg', upload_to='image/%Y/%m'),
        ),
    ]
