# Generated by Django 2.1.8 on 2020-04-13 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='主机IP信息')),
                ('hostname', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='操作系统主机名')),
                ('is_online', models.BooleanField(default=True)),
                ('ssh_port', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='ssh登录的端口')),
                ('ssh_user', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='ssh登录的用户')),
                ('ssh_passwd', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ssh登录的密码')),
                ('cpu_cores', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='cpu核数')),
                ('mem_total', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='内存总大小')),
                ('disk_total', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='磁盘总大小')),
                ('cpu_status', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='cpu使用率')),
                ('mem_status', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='内存使用率')),
                ('disk_status', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='磁盘使用率')),
                ('desc', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='描述信息')),
                ('system_time', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='系统当前时间')),
                ('up_time', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='系统运行时间')),
                ('system_ver', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='操作系统版本')),
                ('mac_address', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='mac地址')),
                ('sn', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='SN－主机的唯一标示')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='制造商')),
                ('cpu_info', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='cpu型号')),
            ],
            options={
                'verbose_name': '资产信息表',
                'verbose_name_plural': '资产信息表',
            },
        ),
        migrations.CreateModel(
            name='ComputerRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='机房名称')),
            ],
            options={
                'verbose_name': '机房表',
                'verbose_name_plural': '机房表',
            },
        ),
        migrations.AddField(
            model_name='assetsinfo',
            name='computer_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.ComputerRoom', verbose_name='所在机房'),
        ),
    ]
