# Generated by Django 2.1.8 on 2020-04-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetsinfo_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsinfo',
            name='manufacturer',
            field=models.CharField(blank=True, default='Unknow', max_length=256, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='assetsinfo',
            name='product',
            field=models.CharField(blank=True, default='Unknow', max_length=256, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='assetsinfo',
            name='sn',
            field=models.CharField(blank=True, default='Unknow', max_length=64, null=True, verbose_name='SN－主机的唯一标示'),
        ),
    ]
