# Generated by Django 2.1.8 on 2020-04-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200414_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsinfo',
            name='desc',
            field=models.CharField(blank=True, default='Unknow', max_length=100, null=True, verbose_name='描述信息'),
        ),
    ]
