# Generated by Django 2.1.8 on 2020-04-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200414_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsinfo',
            name='system_ver',
            field=models.CharField(blank=True, default='系统版本', max_length=256, null=True, verbose_name='操作系统版本'),
        ),
    ]
