# Generated by Django 2.1.8 on 2020-04-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200414_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsinfo',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='assetsinfo',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
