# Generated by Django 2.1.8 on 2020-04-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20200421_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsinfo',
            name='ssh_passwd',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='password'),
        ),
    ]
